services:
#    karaoke.example:
#        class: KaraokeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     karaoke_file_manager:
         class: KaraokeBundle\Services\KaraokeFileManager

     karaoke_time_manager:
         class: KaraokeBundle\Services\KaraokeTimeManager
